package constants

const OAUTH_TOKEN = "GOTWI_OAUTH_TOKEN"
const OAUTH_TOKEN_SECRET = "GOTWI_OAUTH_TOKEN_SECRET"

const END_DATE = "END_DATE"
const TWEET_TEMPLATE = "TWEET_TEMPLATE"
const POST_TIME = "POST_TIME"